### ISSUE TITLE
not working in 0.8?

### ISSUE THREAD

**Issue by kesla** [c4milo/node-webkit-agent#11]
Hi!

I ran the webkit-agent in node 0.6.19 (mac os X) without any problems but when I then upgraded node to 0.8.4 it didnt' work anymore.
It's when I'm stopping a CPU Profile that I get an error in the process that I'm profiling.

The error that I'm seeing is this:

yld: lazy symbol binding failed: Symbol not found: __ZN2v814ObjectTemplate11SetAccessorENS_6HandleINS_6StringEEEPFNS1_INS_5ValueEEENS_5LocalIS2_EERKNS_12AccessorInfoEEPFvS7_NS6_IS4_EESA_ES5_NS_13AccessControlENS_17PropertyAttributeE
  Referenced from: /Users/davidbjorklund/Dropbox/projects/uniqad/node_modules/webkit-devtools-agent/node_modules/v8-profiler/build/Release/profiler.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v814ObjectTemplate11SetAccessorENS_6HandleINS_6StringEEEPFNS1_INS_5ValueEEENS_5LocalIS2_EERKNS_12AccessorInfoEEPFvS7_NS6_IS4_EESA_ES5_NS_13AccessControlENS_17PropertyAttributeE
  Referenced from: /Users/davidbjorklund/Dropbox/projects/uniqad/node_modules/webkit-devtools-agent/node_modules/v8-profiler/build/Release/profiler.node
  Expected in: dynamic lookup
